"""removed url

Revision ID: 59825fe942f1
Revises: dbf57188d0db
Create Date: 2022-05-29 16:25:48.727590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59825fe942f1'
down_revision = 'dbf57188d0db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'url')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('url', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
