"""removed type

Revision ID: dbf57188d0db
Revises: e4c3e706a588
Create Date: 2022-05-29 14:43:40.889879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dbf57188d0db'
down_revision = 'e4c3e706a588'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('type', sa.VARCHAR(), nullable=False))
    # ### end Alembic commands ###
